/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author aluno
 */
public class TelaSistemaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaSistemaPrincipal
     */
    public TelaSistemaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCadastroCliente = new javax.swing.JMenuItem();
        menuItemConsultaCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemCadastroAutomovel = new javax.swing.JMenuItem();
        menuItemConsultaAutomoveis = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemCadastroRevisao = new javax.swing.JMenuItem();
        menuItemConsultaRevisao = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonSair.setFont(new java.awt.Font("Source Sans Pro", 1, 12)); // NOI18N
        buttonSair.setText("Sair");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("MW Automóveis");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mw.png"))); // NOI18N

        jLabel3.setText("By Lucas Pagnoncelli");

        jMenu1.setText("Cliente");

        menuItemCadastroCliente.setText("Cadastro");
        jMenu1.add(menuItemCadastroCliente);

        menuItemConsultaCliente.setText("Consulta");
        jMenu1.add(menuItemConsultaCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Automovel");

        menuItemCadastroAutomovel.setText("Cadastro");
        jMenu2.add(menuItemCadastroAutomovel);

        menuItemConsultaAutomoveis.setText("Consulta");
        jMenu2.add(menuItemConsultaAutomoveis);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Revisão");

        menuItemCadastroRevisao.setText("Cadastro");
        jMenu3.add(menuItemCadastroRevisao);

        menuItemConsultaRevisao.setText("Consulta");
        jMenu3.add(menuItemConsultaRevisao);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addComponent(buttonSair)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buttonSair))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem menuItemCadastroAutomovel;
    public javax.swing.JMenuItem menuItemCadastroCliente;
    public javax.swing.JMenuItem menuItemCadastroRevisao;
    public javax.swing.JMenuItem menuItemConsultaAutomoveis;
    public javax.swing.JMenuItem menuItemConsultaCliente;
    public javax.swing.JMenuItem menuItemConsultaRevisao;
    // End of variables declaration//GEN-END:variables
}
